DROP TABLE IF EXISTS user_as_access;

DROP TABLE IF EXISTS notebook_contains;

DROP TABLE IF EXISTS versions;

DROP TABLE IF EXISTS notes;

DROP TABLE IF EXISTS notebooks;

DROP TABLE IF EXISTS users;